### ISSUE TITLE
ReportingApps don't handle higher DPI on display scale other then 100%

### ISSUE THREAD

**Issue by MaciFla** [VFPX/ReportingApps#2]
Although the problem seems to be solved with the 2014.07.04 Release

> This release fixes a bug in ReportOutput.app and ReportBuilder.app that didn't handle higher DPI displays properly (thanks to Joel Leach).

If we have ReportBehavior set to 90, and system display is set to scale to something greater then 100%, for example 125%, the report will be truncated to the right (both preview and print).
Tested on 1920/1080 display resolution, on a 15,6 inch monitor and 125% scaling, with Visual Fox versions 9, 9SP1, 9SP2, 9SP2 Hotfix 3, with Reporting apps which came with each version, and with the current version from this repository.

**Comment by brianmhiatt** [comment]
FYI I am still seeing same thing MaciFla is.  Has anyone solved this yet?
I did find this attempt to fix it in the reportoutput code.  Will need to analyze to see why not working for me.
	oRec.P_START   = m.iStart
*** 07/04/2014: as per Joel Leach: this calculates the correct band when using higher DPI settings
***	oRec.P_STOP    = m.iStart + oRec.P_HEIGHT + BAND_SEPARATOR_HEIGHT_PIXELS - 1
	oRec.P_STOP    = m.iStart + oRec.P_HEIGHT + round(BAND_SEPARATOR_HEIGHT_PIXELS  * This.ScreenDPI/96, 0) - 1
	iStart         = oRec.P_STOP + 1

**Comment by JoelLeach** [comment]
The fix I did back in 2014 was for a different issue where fields could be placed in the wrong band due to DPI scaling. The truncation into the preview window continues to be a problem. You can work around the problem by handling DPI scaling yourself instead of letting Windows do it.  Tracy Pearson did a session on this at Virtual Fox Fest (https://www.youtube.com/watch?v=1vuNRN21mMk) and António Lopes wrote a library to help (https://github.com/atlopes/DPIAwareManager). For what it's worth, XFRX fixed this issue in their preview window, but it took them a lot of effort and code to resolve.

For posterity, here's more info on the fix from 2014:

Apparently, the Fox Team made some changes to support high DPI settings in the FFC for VFP 9 SP1, but I found a spot they missed.  You would likely never run across this problem unless you were doing some reporting magic… which of course Cathy Pountney (who worked for us at the time) tends to do. :)

The FRXCursor class has code that calculates what band each object (field) is in.  With high DPI settings, each calculation is slightly off.  Eventually, this can add up and an object can be calculated in the wrong band.  The more bands you have, the more likely you are to run into a problem, and it tends to happen in the lower bands (group footer, summary).  Even then, you’re not likely to see the problem because VFP has already calculated the positioning.  Enter Cathy’s magic.  She wrote code that imports the header and footer from a “template” FRX, and then repositions everything else on the report.  Suddenly, it matters which band FRXCursor thinks an object is in, and some objects can render in the wrong band.

The fix is in the FRXCursor.CreateBandCursor() method in _FRXCursor.vcx.  Replace the following code…

      oRec.P_STOP    = m.iStart + oRec.P_HEIGHT + BAND_SEPARATOR_HEIGHT_PIXELS - 1

with

      oRec.P_STOP    = m.iStart + oRec.P_HEIGHT + Round(BAND_SEPARATOR_HEIGHT_PIXELS  * This.ScreenDPI/96, 0) - 1

In my tests, everything ends up in the right band.
